package user.validate

import com.techmaster.sparrow.rules.beans.UserRuleBean;
import java.time.LocalDateTime;

dialect "java"

function boolean nullOrEmpty (Object obj) {
   return (obj == null || obj.toString().trim() == "");
}

rule "Validate First Name"

   when
      $user : UserRuleBean( firstName == null || firstName == "" )
   then
      $user.getRuleResultBean().setError("firstName", "First name is required");
end

rule "Validate Last Name"

   when
      $user : UserRuleBean( lastName == null || lastName == "" )
   then
      $user.getRuleResultBean().setError("lastName", "Last name is required");
end