package user.validate

import com.techmaster.sparrow.rules.beans.UserRuleBean;

rule "Validate First Name"
   when
      user : UserRuleBean( firstName == null )
   then
      user.getRuleResultBean().setError("firstName", "First name is required");
      update(user)
end

rule "Validate Last Name"

   when
      user : UserRuleBean( lastName == null )
   then
      user.getRuleResultBean().setError("lastName", "Last name is required");
      update(user)
end